name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Setup dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test

      - name: Run deploy
        run: make deploy

      - name: Run docs
        run: make docs
