name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Setup dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          user: mostly-harmless-ai
          email: noreply@mostly-harmless.ai
          global: true
          actor: apiad
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Deploy tasks
        run: make deploy

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MOSTLY_HARMLESS_DOCS }}
          external_repository: mostly-harmless-ai/mostly-harmless-ai.github.io
          publish_branch: docs
          publish_dir: ./site
